---
# yamllint disable rule:line-length
default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/jameswoolfenden/ghat
    rev: 783f1adff1b67e121f0a3af745979b0ccab69e11 # v0.1.31
    hooks:
      - id: ghat-go
      - id: ghat-go-sift
