---
# yamllint disable rule:line-length
name: Terraform Pull Request
on:
  workflow_call:

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.find.outputs.dirs }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - id: find
        run: |
          dirs=$(find example -maxdepth 1 -mindepth 1 -type d | sort | jq -R -s -c 'split("\n")[:-1]')
          echo "dirs=$dirs" >> $GITHUB_OUTPUT

  terraform:
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{ fromJson(needs.discover.outputs.dirs) }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: '0'
      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ matrix.dir }}
      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ matrix.dir }}

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: '0'
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.11
      - name: Symlink tofu as terraform
        run: sudo ln -sf "$(which tofu)" /usr/local/bin/terraform
      - run: |
          mkdir "$GITHUB_WORKSPACE/bin"
          curl -sSLo terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.22.0/terraform-docs-v0.22.0-linux-amd64.tar.gz
          tar -xvf terraform-docs.tar.gz --directory "$GITHUB_WORKSPACE/bin"
          chmod +x "$GITHUB_WORKSPACE/bin/terraform-docs"
          curl -sSLo actionlint.tar.gz https://github.com/rhysd/actionlint/releases/download/v1.7.12/actionlint_1.7.12_linux_amd64.tar.gz
          tar -xvf actionlint.tar.gz --directory "$GITHUB_WORKSPACE/bin"
          chmod +x "$GITHUB_WORKSPACE/bin/actionlint"
          echo "$GITHUB_WORKSPACE/bin" >> "$GITHUB_PATH"
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
